-- public."Books" definition

-- Drop table

-- DROP TABLE public."Books";

CREATE TABLE public."Books" (
	"Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	"Title" text NOT NULL,
	"Descriptions" text NULL DEFAULT ''::text,
	"Price_EndDate" date NULL,
	"Price_Price" numeric NOT NULL DEFAULT 0.0,
	"Price_StartDate" date NOT NULL DEFAULT '-infinity'::date,
	CONSTRAINT "PK_Books" PRIMARY KEY ("Id")
);